### PR TITLE
Rider 2021.2 support

### PR DESCRIPTION
**Pull request by maartenba**
* Works against RC version
* Potentially fixes https://plugins.jetbrains.com/plugin/10183--net-core-user-secrets/reviews#review=49765 (using `File.resolve` now to track file paths)

### CODE REVIEW

**Comment by seclerp** [comment]
@maartenba the implementation is refactored a bit 😅 and the actual version for now is `1.2.0`

**Comment by maartenba** [comment]
Rebased, and here we are again :-)

**Comment by seclerp** [comment]
I think that version of the plugin in your PR should be `1.2.1`, because `1.2.0` was already released couple of days ago :)

**Comment by maartenba** [comment]
There you go @seclerp

**Comment by seclerp** [comment]
@maartenba I could confirm that the plugin already works with Rider 2021.2, but I believe that your changes are needed anyway to potentially fix an issue that you addressed, just want to confirm that it already works on the newest version of Rider :)

**Comment by maartenba** [comment]
Fresh version: https://github.com/Witik/RiderUserSecrets/pull/25

**Pull request closed without merging**
